
import java.awt.Color;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Truong
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    private String user;
    private String hoten;
    DecimalFormat formatter = new DecimalFormat("###,###,###"); 
    public Admin(String user, String hoten) {
        initComponents();
        this.user = user;
        txtXinChao.setText("Chào "+hoten);
        setLocationRelativeTo(null);
        initTable();
        initTableSP();
        jTabbedPane1.setSelectedIndex(0);
        lblNhansu.setBackground(Color.green);
        jLabel2.setBackground(Color.yellow);
        jLabel3.setBackground(Color.yellow);
        setButton();
        renderToTableEmploy(tblModel);
        initTableTK();
    }
    
    public Admin() {
        initComponents();
        setLocationRelativeTo(null);
        initTable();
        initTableSP();
        jTabbedPane1.setSelectedIndex(0);
        lblNhansu.setBackground(Color.green);
        jLabel2.setBackground(Color.yellow);
        jLabel3.setBackground(Color.yellow);
        setButton();
        renderToTableEmploy(tblModel);
        initTableTK();
    }
    
    public void setButton(){
        btnSua.setEnabled(false);
        btnXoa.setEnabled(false);
        btnSuaSP.setEnabled(false);
        btnXoaSP.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        dlgDMK = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        txtMatKhauMoi = new javax.swing.JPasswordField();
        txtMatKhauMoi2 = new javax.swing.JPasswordField();
        txtMatKhauCu = new javax.swing.JPasswordField();
        txtMKC = new javax.swing.JLabel();
        txtMKM = new javax.swing.JLabel();
        txtMKM1 = new javax.swing.JLabel();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jTextField6 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        lblNhansu = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtXinChao = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMain = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtTaiKhoan = new javax.swing.JTextField();
        txtTen = new javax.swing.JTextField();
        txtNamSinh = new javax.swing.JTextField();
        txtMucLuong = new javax.swing.JTextField();
        rdoNam = new javax.swing.JRadioButton();
        rdoNu = new javax.swing.JRadioButton();
        rdoQuanly = new javax.swing.JRadioButton();
        rdoThuNgan = new javax.swing.JRadioButton();
        rdoNhanVien = new javax.swing.JRadioButton();
        txtMatKhau = new javax.swing.JPasswordField();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblThongKe = new javax.swing.JTable();
        cbxTuNgay = new javax.swing.JComboBox<>();
        cbxDenNgay = new javax.swing.JComboBox<>();
        cbxTuThang = new javax.swing.JComboBox<>();
        cbxDenThang = new javax.swing.JComboBox<>();
        cbxTuNam = new javax.swing.JComboBox<>();
        cbxDenNam = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txtDoanhThuAn = new javax.swing.JTextField();
        txtDoanhThuUong = new javax.swing.JTextField();
        txtDoanhThu = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        rdoNuoc = new javax.swing.JRadioButton();
        rdoAn = new javax.swing.JRadioButton();
        txtMASP = new javax.swing.JTextField();
        txtTenSP = new javax.swing.JTextField();
        txtGiaSP = new javax.swing.JTextField();
        txtDonViSP = new javax.swing.JTextField();
        btnThemSP = new javax.swing.JButton();
        btnXoaSP = new javax.swing.JButton();
        btnSuaSP = new javax.swing.JButton();
        btnHuySP = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSP = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        dlgDMK.setTitle("ĐỔI MẬT KHẨU");
        dlgDMK.setLocation(new java.awt.Point(400, 250));
        dlgDMK.setMinimumSize(new java.awt.Dimension(520, 300));
        dlgDMK.setModal(true);
        dlgDMK.setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 153));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Mật khẩu cũ");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Mật khẩu mới");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Nhập lại mật khẩu mới");

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton7.setText("Xác nhận");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton8.setText("Thoát");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        txtMKC.setForeground(new java.awt.Color(255, 0, 0));
        txtMKC.setText(" ");

        txtMKM.setForeground(new java.awt.Color(255, 0, 0));
        txtMKM.setText(" ");

        txtMKM1.setForeground(new java.awt.Color(255, 0, 0));
        txtMKM1.setText(" ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(61, 61, 61)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMKC)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtMatKhauMoi)
                                .addComponent(txtMatKhauCu, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))
                            .addComponent(txtMKM1)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMKM)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtMatKhauMoi2)))))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(txtMatKhauCu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(txtMKC)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtMatKhauMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMKM1)
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtMatKhauMoi2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(txtMKM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton8))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dlgDMKLayout = new javax.swing.GroupLayout(dlgDMK.getContentPane());
        dlgDMK.getContentPane().setLayout(dlgDMKLayout);
        dlgDMKLayout.setHorizontalGroup(
            dlgDMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dlgDMKLayout.setVerticalGroup(
            dlgDMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTextField6.setText("jTextField6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUẢN LÝ");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));

        lblNhansu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNhansu.setForeground(new java.awt.Color(51, 0, 255));
        lblNhansu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNhansu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nhansu_2.png"))); // NOI18N
        lblNhansu.setText("NHÂN SỰ");
        lblNhansu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblNhansu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblNhansu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblNhansu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblNhansu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNhansuMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sanpham_1.PNG"))); // NOI18N
        jLabel2.setText("SẢN PHẨM");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/thongke_2.png"))); // NOI18N
        jLabel3.setText("THỐNG KÊ");
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        txtXinChao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtXinChao.setForeground(new java.awt.Color(102, 0, 255));
        txtXinChao.setText("Chào");

        jButton5.setBackground(new java.awt.Color(255, 255, 153));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 51, 51));
        jButton5.setText("Đăng xuất");
        jButton5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5.setFocusPainted(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(255, 255, 153));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 51, 51));
        jButton6.setText("Đổi mật khẩu");
        jButton6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton6.setDoubleBuffered(true);
        jButton6.setFocusPainted(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(txtXinChao)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblNhansu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
            .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(txtXinChao)
                .addGap(15, 15, 15)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblNhansu)
                .addGap(40, 40, 40)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jLabel3)
                .addGap(26, 26, 26))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 560));

        tblMain.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblMain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMainMouseClicked(evt);
            }
        });
        tblMain.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblMainKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblMain);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Tài khoản");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Mật khẩu");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Họ tên");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Năm sinh");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Giới tính");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Loại tài khoản");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Mức lương");

        buttonGroup1.add(rdoNam);
        rdoNam.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rdoNam.setSelected(true);
        rdoNam.setText("Nam");

        buttonGroup1.add(rdoNu);
        rdoNu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rdoNu.setText("Nữ");

        buttonGroup2.add(rdoQuanly);
        rdoQuanly.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rdoQuanly.setText("Quản lý");

        buttonGroup2.add(rdoThuNgan);
        rdoThuNgan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rdoThuNgan.setText("Thu ngân");

        buttonGroup2.add(rdoNhanVien);
        rdoNhanVien.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rdoNhanVien.setSelected(true);
        rdoNhanVien.setText("Nhân viên");

        btnThem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("Hủy");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("VNĐ/Giờ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addGap(76, 76, 76)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTen)
                            .addComponent(txtNamSinh)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel9))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rdoQuanly)
                                    .addComponent(rdoNu))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(rdoThuNgan)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rdoNhanVien))
                                    .addComponent(rdoNam))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(btnThem)
                                        .addGap(24, 24, 24)
                                        .addComponent(btnSua)
                                        .addGap(27, 27, 27)
                                        .addComponent(btnXoa))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(39, 39, 39)
                                        .addComponent(txtMucLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton4)
                                    .addComponent(jLabel1)))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(72, 72, 72)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTaiKhoan)
                            .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(189, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtNamSinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(rdoNam)
                    .addComponent(rdoNu))
                .addGap(8, 8, 8)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(rdoQuanly)
                    .addComponent(rdoThuNgan)
                    .addComponent(rdoNhanVien))
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtMucLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnSua)
                    .addComponent(btnXoa)
                    .addComponent(jButton4))
                .addGap(13, 13, 13)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("tab1", jPanel3);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setText("Từ:");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setText("Đến:");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setText("Ngày");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setText("Ngày");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setText("Tháng");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setText("Tháng");

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setText("Năm");

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel26.setText("Năm");

        tblThongKe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Ngày", "Số hóa đơn", "Người lập", "Doanh thu ăn", "Doanh thu uống"
            }
        ));
        jScrollPane3.setViewportView(tblThongKe);

        cbxTuNgay.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbxTuNgay.setForeground(new java.awt.Color(0, 0, 255));
        cbxTuNgay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        cbxDenNgay.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbxDenNgay.setForeground(new java.awt.Color(0, 0, 255));
        cbxDenNgay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        cbxTuThang.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbxTuThang.setForeground(new java.awt.Color(0, 0, 255));
        cbxTuThang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        cbxDenThang.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbxDenThang.setForeground(new java.awt.Color(0, 0, 255));
        cbxDenThang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        cbxTuNam.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbxTuNam.setForeground(new java.awt.Color(0, 0, 255));
        cbxTuNam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2021", "2022", "2023", "2024", "2025" }));

        cbxDenNam.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbxDenNam.setForeground(new java.awt.Color(0, 0, 255));
        cbxDenNam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2021", "2022", "2023", "2024", "2025" }));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/kinhlup.jpg"))); // NOI18N
        jButton1.setText("       Xem");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel27.setText("Tổng doanh thu ăn:");

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel28.setText("Tổng doanh thu uống:");

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel29.setText("Tổng doanh thu:");

        txtDoanhThuAn.setEditable(false);
        txtDoanhThuAn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtDoanhThuAn.setForeground(new java.awt.Color(0, 0, 255));

        txtDoanhThuUong.setEditable(false);
        txtDoanhThuUong.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtDoanhThuUong.setForeground(new java.awt.Color(0, 0, 255));

        txtDoanhThu.setEditable(false);
        txtDoanhThu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtDoanhThu.setForeground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane3)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jSeparator3)
                        .addGap(55, 55, 55))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                                .addGap(21, 21, 21)
                                .addComponent(jLabel22))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel21)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxTuNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxDenNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxTuThang, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxDenThang, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxTuNam, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxDenNam, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27)
                            .addComponent(jLabel28)
                            .addComponent(jLabel29))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtDoanhThuAn)
                            .addComponent(txtDoanhThuUong)
                            .addComponent(txtDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(jLabel21)
                            .addComponent(jLabel25)
                            .addComponent(cbxTuNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxTuNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23)
                            .addComponent(cbxTuThang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel26)
                                    .addComponent(cbxDenNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel24)
                                    .addComponent(cbxDenThang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxDenNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(txtDoanhThuAn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(txtDoanhThuUong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(txtDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        jTabbedPane1.addTab("tab3", jPanel5);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Mã Sản Phẩm");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Tên Sản Phẩm");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Giá");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("Đơn vị");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("Loại");

        buttonGroup3.add(rdoNuoc);
        rdoNuoc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rdoNuoc.setSelected(true);
        rdoNuoc.setText("Nước uống");
        rdoNuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoNuocActionPerformed(evt);
            }
        });

        buttonGroup3.add(rdoAn);
        rdoAn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rdoAn.setText("Ăn vặt");
        rdoAn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoAnActionPerformed(evt);
            }
        });

        btnThemSP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnThemSP.setText("Thêm");
        btnThemSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemSPActionPerformed(evt);
            }
        });

        btnXoaSP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnXoaSP.setText("Xóa");
        btnXoaSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaSPActionPerformed(evt);
            }
        });

        btnSuaSP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSuaSP.setText("Sửa");
        btnSuaSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaSPActionPerformed(evt);
            }
        });

        btnHuySP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnHuySP.setText("Hủy");
        btnHuySP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuySPActionPerformed(evt);
            }
        });

        tblSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSPMouseClicked(evt);
            }
        });
        tblSP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblSPKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tblSP);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtGiaSP, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                    .addComponent(rdoNuoc)
                                    .addGap(18, 18, 18)
                                    .addComponent(rdoAn))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtTenSP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                                    .addComponent(txtMASP, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addComponent(txtDonViSP))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(btnThemSP)
                        .addGap(59, 59, 59)
                        .addComponent(btnXoaSP)
                        .addGap(47, 47, 47)
                        .addComponent(btnSuaSP)
                        .addGap(57, 57, 57)
                        .addComponent(btnHuySP)
                        .addGap(112, 112, 112))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMASP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addGap(33, 33, 33))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtGiaSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDonViSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoNuoc)
                    .addComponent(rdoAn)
                    .addComponent(jLabel18))
                .addGap(14, 14, 14)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemSP)
                    .addComponent(btnXoaSP)
                    .addComponent(btnSuaSP)
                    .addComponent(btnHuySP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("tab2", jPanel4);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, -25, 710, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        txtTaiKhoan.setText("");
        txtTen.setText("");
        txtMatKhau.setText("");
        txtNamSinh.setText("");
        txtMucLuong.setText("");
        rdoNam.setSelected(true);
        rdoNhanVien.setSelected(true);
        txtMatKhau.setEnabled(true);
        txtTaiKhoan.setEnabled(true);
        btnThem.setEnabled(true);
        btnSua.setEnabled(false);
        btnXoa.setEnabled(false);
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        dlgDMK.setVisible(true);
        dlgDMK.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton6ActionPerformed
    
    
    public void renderToTableEmploy(DefaultTableModel tblModel){
        tblModel.setRowCount(0);
        String pw="";
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String Url = "jdbc:sqlserver://localhost:1433;databaseName=QUANLYCUAHANG;user=sa;password=sa";
            Connection conn = DriverManager.getConnection(Url);
            String sql = "select * from NGUOIDUNG" ;
            PreparedStatement st = conn.prepareStatement(sql);
            ResultSet rs = st.executeQuery();
            while (rs.next()){
                Object[] row = new Object[]{
                    rs.getString(1), rs.getString(3), rs.getInt(4),rs.getInt(5) ,
                    rs.getInt(6),rs.getInt(7)
                };
            tblModel.addRow(row);
            }
           
            rs.close();
            st.close();
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
        tblModel.fireTableDataChanged();
    }
    
    public void renderToTableSP(DefaultTableModel tblModel){
        tblModelSP.setRowCount(0);
       
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String Url = "jdbc:sqlserver://localhost:1433;databaseName=QUANLYCUAHANG;user=sa;password=sa";
            Connection conn = DriverManager.getConnection(Url);
            String sql = "select * from SANPHAM" ;
            PreparedStatement st = conn.prepareStatement(sql);
            ResultSet rs = st.executeQuery();
            while (rs.next()){
                Object[] row = new Object[]{
                    rs.getString(1), rs.getString(2), rs.getInt(3),rs.getString(4) ,
                    rs.getInt(5)
                };
            tblModelSP.addRow(row);
            }
           
            rs.close();
            st.close();
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
        tblModelSP.fireTableDataChanged();
    }
    
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        String pw="";
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String Url = "jdbc:sqlserver://localhost:1433;databaseName=QUANLYCUAHANG;user=sa;password=sa";
            Connection conn = DriverManager.getConnection(Url);
            String sql = "select MATKHAU from NGUOIDUNG WHERE TAIKHOAN=?" ;
            PreparedStatement st = conn.prepareStatement(sql);
            st.setString(1,user);
            ResultSet rs = st.executeQuery();
            if (rs.next())
            pw = rs.getString(1);
            rs.close();
            st.close();
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
        if(!pw.equals(txtMatKhauCu.getText()))
            txtMKC.setText("SAI MẬT KHẨU!");
        else{
            txtMKC.setText(" ");
            if (txtMatKhauMoi.getText().trim().isEmpty()){
                txtMKM1.setText("KHÔNG ĐƯỢC ĐỂ TRỐNG!");
            }else
            if(!txtMatKhauMoi.getText().equals(txtMatKhauMoi2.getText())){
                txtMKM.setText("KHÔNG KHỚP!");
                txtMKM1.setText(" ");
            }
            else {
                
                txtMKM.setText(" ");
                try {
                    Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                    String Url = "jdbc:sqlserver://localhost:1433;databaseName=QUANLYCUAHANG;user=sa;password=sa";
                    Connection conn = DriverManager.getConnection(Url);
                    String sql = "UPDATE NGUOIDUNG SET MATKHAU=? WHERE TAIKHOAN=?" ;
                    PreparedStatement st = conn.prepareStatement(sql);
                    st.setString(1,txtMatKhauMoi.getText());
                    st.setString(2,user);
                    int dong = st.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Thành công!");
                    txtMatKhauCu.setText("");
                    txtMatKhauMoi.setText("");
                    txtMatKhauMoi2.setText("");
                    txtMKM1.setText(" ");
                    dlgDMK.dispose();
                    st.close();
                    conn.close();
                } catch (Exception e) {
                    e.printStackTrace();
                }

            }
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        dlgDMK.setVisible(false);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        int yes= JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn Đăng xuất không?", "THÔNG BÁO", JOptionPane.YES_NO_OPTION);
        if (yes==0){
            this.dispose();
            Dangnhap dn = new Dangnhap();
            dn.setVisible(true);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void lblNhansuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNhansuMouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
        lblNhansu.setBackground(Color.green);
        jLabel2.setBackground(Color.yellow);
        jLabel3.setBackground(Color.yellow);
        
    }//GEN-LAST:event_lblNhansuMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);
        lblNhansu.setBackground(Color.yellow);
        jLabel2.setBackground(Color.green);
        jLabel3.setBackground(Color.yellow);
        renderToTableSP(tblModelSP);
        
        
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
        lblNhansu.setBackground(Color.yellow);
        jLabel2.setBackground(Color.yellow);
        jLabel3.setBackground(Color.green);
    }//GEN-LAST:event_jLabel3MouseClicked
    private int checkNamSinh(String s){
        int ns = -1;
        try{
            ns = Integer.parseInt(s);
            if (ns<1900||ns>2021){
                return -1;
            }
        }
        catch(Exception e){
            return -1;
        }
        return ns;
    }
    private int checkML(String s){
        int ml = -1;
        try{
            ml = Integer.parseInt(s);
            if(ml<0) ml = -1;
        }
        catch(Exception e){
            return -1;
        }
        return ml;
    }
    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        
        String taikhoan,matkhau,ten;
        int gioitinh,loaitaikhoan,namsinh,mucluong;
        taikhoan = txtTaiKhoan.getText().trim();
        matkhau = txtMatKhau.getText().trim();
        ten = txtTen.getText().trim();
        namsinh = checkNamSinh(txtNamSinh.getText());
        mucluong = checkML(txtMucLuong.getText());
        if(rdoNam.isSelected()) gioitinh = 1; else gioitinh = 0;
        if(rdoNhanVien.isSelected()) loaitaikhoan = 2;
            else if(rdoQuanly.isSelected()) loaitaikhoan = 0;
            else loaitaikhoan = 1;
        if (taikhoan.isEmpty()){
            JOptionPane.showMessageDialog(this,"Tài khoản không được để trống","CẢNH BÁO",JOptionPane.ERROR_MESSAGE);
            txtTaiKhoan.requestFocus();
        }else
        if (matkhau.isEmpty()){
            JOptionPane.showMessageDialog(this,"Mật khẩu không được để trống","CẢNH BÁO",JOptionPane.ERROR_MESSAGE);
            txtMatKhau.requestFocus();
        }else
        if (ten.isEmpty()){
            JOptionPane.showMessageDialog(this,"Họ Tên không được để trống","CẢNH BÁO",JOptionPane.ERROR_MESSAGE);
            txtTen.requestFocus();
        }else
        if (namsinh==-1){
            JOptionPane.showMessageDialog(this,"Năm sinh không hợp lệ (1900-2021)","CẢNH BÁO",JOptionPane.ERROR_MESSAGE);
            txtNamSinh.requestFocus();
        }else
        if (mucluong==-1){
            JOptionPane.showMessageDialog(this,"Mức lương không hợp lệ","CẢNH BÁO",JOptionPane.ERROR_MESSAGE);
            txtMucLuong.requestFocus();
        } else
        
        // thêm
        try {
                    Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                    String Url = "jdbc:sqlserver://localhost:1433;databaseName=QUANLYCUAHANG;user=sa;password=sa";
                    Connection conn = DriverManager.getConnection(Url);
                    String sql="INSERT INTO NGUOIDUNG VALUES(?,?,?,?,?,?,?)";
                    PreparedStatement st = conn.prepareStatement(sql);
                    st.setString(1, taikhoan);
                    st.setString(2, matkhau);
                    st.setString(3, ten);
                    st.setInt(4, namsinh);
                    st.setInt(5, gioitinh);
                    st.setInt(6, loaitaikhoan);
                    st.setInt(7, mucluong);
                    int sodong=st.executeUpdate();
                    JOptionPane.showMessageDialog(this,"Thêm thành công!");
                    renderToTableEmploy(tblModel);
                    st.close();
                    conn.close();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this,"Tài khoản đã tồn tại","CẢNH BÁO",JOptionPane.ERROR_MESSAGE);
                }
        
        
    }//GEN-LAST:event_btnThemActionPerformed

    private void tblMainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMainMouseClicked
        // TODO add your handling code here:
        int row = tblMain.getSelectedRow();
        txtTaiKhoan.setText(tblMain.getValueAt(row, 0).toString());
        txtTen.setText(tblMain.getValueAt(row, 1).toString());
        txtMatKhau.setText("");
        txtNamSinh.setText(tblMain.getValueAt(row, 2).toString());
        txtMucLuong.setText(tblMain.getValueAt(row, 5).toString());
        if (tblMain.getValueAt(row, 3).toString().equals("1"))
            rdoNam.setSelected(true);
        else 
            rdoNu.setSelected(true);
        if (tblMain.getValueAt(row, 4).toString().equals("0"))
            rdoQuanly.setSelected(true);
        else 
        if (tblMain.getValueAt(row, 4).toString().equals("1"))
            rdoThuNgan.setSelected(true);
        else
            rdoNhanVien.setSelected(true);
        
        txtMatKhau.setEnabled(false);
        txtTaiKhoan.setEnabled(false);
        btnThem.setEnabled(false);
        btnSua.setEnabled(true);
        btnXoa.setEnabled(true);
    }//GEN-LAST:event_tblMainMouseClicked

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        String ten,taikhoan;
        int gioitinh,loaitaikhoan,namsinh,mucluong;
        
        taikhoan=txtTaiKhoan.getText();
        ten = txtTen.getText().trim();
        namsinh = checkNamSinh(txtNamSinh.getText());
        mucluong = checkML(txtMucLuong.getText());
        if(rdoNam.isSelected()) gioitinh = 1; else gioitinh = 0;
        if(rdoNhanVien.isSelected()) loaitaikhoan = 2;
            else if(rdoQuanly.isSelected()) loaitaikhoan = 0;
            else loaitaikhoan = 1;
        
        if (ten.isEmpty()){
            JOptionPane.showMessageDialog(this,"Họ Tên không được để trống","CẢNH BÁO",JOptionPane.ERROR_MESSAGE);
            txtTen.requestFocus();
        }else
        if (namsinh==-1){
            JOptionPane.showMessageDialog(this,"Năm sinh không hợp lệ (1900-2021)","CẢNH BÁO",JOptionPane.ERROR_MESSAGE);
            txtNamSinh.requestFocus();
        }else
        if (mucluong==-1){
            JOptionPane.showMessageDialog(this,"Mức lương không hợp lệ","CẢNH BÁO",JOptionPane.ERROR_MESSAGE);
            txtMucLuong.requestFocus();
        } 
        else
        
        {
            try {
                    Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                    String Url = "jdbc:sqlserver://localhost:1433;databaseName=QUANLYCUAHANG;user=sa;password=sa";
                    Connection conn = DriverManager.getConnection(Url);
                    String sql = "UPDATE NGUOIDUNG SET Ten=?,Namsinh=?,gioitinh=?,loaitk=?, mucluong=? WHERE TAIKHOAN=?" ;
                    PreparedStatement st = conn.prepareStatement(sql);
                    
                    st.setString(1, ten);
                    st.setInt(2, namsinh);
                    st.setInt(3, gioitinh);
                    st.setInt(4, loaitaikhoan);
                    st.setInt(5,mucluong);
                    st.setString(6, taikhoan);
                    
                    int dong = st.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Thành công!");
                    renderToTableEmploy(tblModel);
                    
                    st.close();
                    conn.close();
                } catch (Exception e) {
                    e.printStackTrace();
                }

            
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        String taikhoan=txtTaiKhoan.getText();
        
        int yes= JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa tài khoản "+txtTaiKhoan.getText(), "THÔNG BÁO", JOptionPane.YES_NO_OPTION);
        
        if(yes==0)
            try {
                    Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                    String Url = "jdbc:sqlserver://localhost:1433;databaseName=QUANLYCUAHANG;user=sa;password=sa";
                    Connection conn = DriverManager.getConnection(Url);
                    String sql = "delete from nguoidung where taikhoan=?;" ;
                    PreparedStatement st = conn.prepareStatement(sql);
                    
                    st.setString(1, taikhoan);
                    
                    
                    int dong = st.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Thành công!");
                    renderToTableEmploy(tblModel);
                    jButton4ActionPerformed(evt);
                    
                    st.close();
                    conn.close();
                } catch (Exception e) {
                    e.printStackTrace();
                }
        
    }//GEN-LAST:event_btnXoaActionPerformed

    private void rdoNuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoNuocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoNuocActionPerformed

    private void rdoAnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoAnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoAnActionPerformed

    private void btnThemSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemSPActionPerformed
        // TODO add your handling code here:
        String masp,tensp, donvi;
        int gia,loai;
        masp = txtMASP.getText().trim();
        tensp = txtTenSP.getText().trim();
        donvi = txtDonViSP.getText().trim();
        gia = checkML(txtGiaSP.getText());
        if(rdoNuoc.isSelected()) loai = 1; else loai = 2;
        
        if (masp.isEmpty()){
            JOptionPane.showMessageDialog(this,"Mã Sản Phẩm không được để trống","CẢNH BÁO",JOptionPane.ERROR_MESSAGE);
            txtMASP.requestFocus();
        }else
        if (tensp.isEmpty()){
            JOptionPane.showMessageDialog(this,"Tên Sản Phẩm không được để trống","CẢNH BÁO",JOptionPane.ERROR_MESSAGE);
            txtTenSP.requestFocus();
        }else
        if (donvi.isEmpty()){
            JOptionPane.showMessageDialog(this,"Đơn Vị không được để trống","CẢNH BÁO",JOptionPane.ERROR_MESSAGE);
            txtDonViSP.requestFocus();
        }else
        if (gia==-1){
            JOptionPane.showMessageDialog(this,"Giá không hợp lệ","CẢNH BÁO",JOptionPane.ERROR_MESSAGE);
            txtGiaSP.requestFocus();
        } else
        
        // thêm
        try {
                    Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                    String Url = "jdbc:sqlserver://localhost:1433;databaseName=QUANLYCUAHANG;user=sa;password=sa";
                    Connection conn = DriverManager.getConnection(Url);
                    String sql="INSERT INTO SANPHAM VALUES(?,?,?,?,?)";
                    PreparedStatement st = conn.prepareStatement(sql);
                    st.setString(1, masp);
                    st.setString(2, tensp);
                    st.setInt(3, gia);
                    st.setString(4, donvi);
                    st.setInt(5, loai);
                    
                    int sodong=st.executeUpdate();
                    JOptionPane.showMessageDialog(this,"Thêm thành công!");
                    renderToTableSP(tblModelSP);
                    st.close();
                    conn.close();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this,"Sản phẩm đã tồn tại","CẢNH BÁO",JOptionPane.ERROR_MESSAGE);
                }
    }//GEN-LAST:event_btnThemSPActionPerformed

    private void tblSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSPMouseClicked
        int row = tblSP.getSelectedRow();
        txtMASP.setText(tblSP.getValueAt(row, 0).toString());
        txtTenSP.setText(tblSP.getValueAt(row, 1).toString());
        txtGiaSP.setText(tblSP.getValueAt(row, 2).toString());
        txtDonViSP.setText(tblSP.getValueAt(row, 3).toString());
        if (tblSP.getValueAt(row, 4).toString().equals("1"))
            rdoNuoc.setSelected(true);
        else 
            rdoAn.setSelected(true);
        txtMASP.setEnabled(false);
        btnThemSP.setEnabled(false);
        btnSuaSP.setEnabled(true);
        btnXoaSP.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_tblSPMouseClicked

    private void btnHuySPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuySPActionPerformed
        // TODO add your handling code here:
        txtMASP.setText("");
        txtTenSP.setText("");
        txtGiaSP.setText("");
        txtDonViSP.setText("");
       
        rdoNuoc.setSelected(true);
        txtMASP.setEnabled(true);
        btnThemSP.setEnabled(true);
        btnSuaSP.setEnabled(false);
        btnXoaSP.setEnabled(false);
    }//GEN-LAST:event_btnHuySPActionPerformed

    private void btnXoaSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaSPActionPerformed
        // TODO add your handling code here:
        String masp=txtMASP.getText();
        
        int yes= JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa sản phẩm "+txtMASP.getText(), "THÔNG BÁO", JOptionPane.YES_NO_OPTION);
        
        if(yes==0)
            try {
                    Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                    String Url = "jdbc:sqlserver://localhost:1433;databaseName=QUANLYCUAHANG;user=sa;password=sa";
                    Connection conn = DriverManager.getConnection(Url);
                    String sql = "delete from sanpham where masp=?;" ;
                    PreparedStatement st = conn.prepareStatement(sql);
                    
                    st.setString(1, masp);
                    
                    
                    int dong = st.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Thành công!");
                    renderToTableSP(tblModelSP);
                    btnHuySPActionPerformed(evt);
                    
                    st.close();
                    conn.close();
                } catch (Exception e) {
                    e.printStackTrace();
                }
        
    }//GEN-LAST:event_btnXoaSPActionPerformed

    private void btnSuaSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaSPActionPerformed
        // TODO add your handling code here:
         String tensp,masp,donvisp;
        int loaisp,giasp;
        
        masp=txtMASP.getText();
        tensp = txtTenSP.getText().trim();
        donvisp = txtDonViSP.getText().trim();
        giasp = checkML(txtGiaSP.getText());
        if(rdoNuoc.isSelected()) loaisp = 1; else loaisp = 2;
        
        if (tensp.isEmpty()){
            JOptionPane.showMessageDialog(this,"Tên Sản Phẩm không được để trống","CẢNH BÁO",JOptionPane.ERROR_MESSAGE);
            txtTen.requestFocus();
        }else
        if (donvisp.isEmpty()){
            JOptionPane.showMessageDialog(this,"Đơn Vị không được để trống","CẢNH BÁO",JOptionPane.ERROR_MESSAGE);
            txtTen.requestFocus();
        }else
        if (giasp==-1){
            JOptionPane.showMessageDialog(this,"Giá không hợp lệ","CẢNH BÁO",JOptionPane.ERROR_MESSAGE);
            txtMucLuong.requestFocus();
        } 
        else
        
        {
            try {
                    Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                    String Url = "jdbc:sqlserver://localhost:1433;databaseName=QUANLYCUAHANG;user=sa;password=sa";
                    Connection conn = DriverManager.getConnection(Url);
                    String sql = "UPDATE SANPHAM SET Ten=?,gia=?,donvi=?,loai=? WHERE masp=?" ;
                    PreparedStatement st = conn.prepareStatement(sql);
                    
                    st.setString(1, tensp);
                    st.setInt(2, giasp);
                    st.setString(3, donvisp);
                    st.setInt(4, loaisp);
                    st.setString(5, masp);
                    
                    int dong = st.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Thành công!");
                    renderToTableSP(tblModelSP);
                    
                    st.close();
                    conn.close();
                } catch (Exception e) {
                    e.printStackTrace();
                }
        }
    }//GEN-LAST:event_btnSuaSPActionPerformed

    private void tblMainKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblMainKeyReleased
        // TODO add your handling code here:
            int row = tblMain.getSelectedRow();
        txtTaiKhoan.setText(tblMain.getValueAt(row, 0).toString());
        txtTen.setText(tblMain.getValueAt(row, 1).toString());
        txtMatKhau.setText("");
        txtNamSinh.setText(tblMain.getValueAt(row, 2).toString());
        txtMucLuong.setText(tblMain.getValueAt(row, 5).toString());
        if (tblMain.getValueAt(row, 3).toString().equals("1"))
            rdoNam.setSelected(true);
        else 
            rdoNu.setSelected(true);
        if (tblMain.getValueAt(row, 4).toString().equals("0"))
            rdoQuanly.setSelected(true);
        else 
        if (tblMain.getValueAt(row, 4).toString().equals("1"))
            rdoThuNgan.setSelected(true);
        else
            rdoNhanVien.setSelected(true);
        
        txtMatKhau.setEnabled(false);
        txtTaiKhoan.setEnabled(false);
        btnThem.setEnabled(false);
        btnSua.setEnabled(true);
        btnXoa.setEnabled(true);
    }//GEN-LAST:event_tblMainKeyReleased

    private void tblSPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblSPKeyReleased
        // TODO add your handling code here:
        int row = tblSP.getSelectedRow();
        txtMASP.setText(tblSP.getValueAt(row, 0).toString());
        txtTenSP.setText(tblSP.getValueAt(row, 1).toString());
        txtGiaSP.setText(tblSP.getValueAt(row, 2).toString());
        txtDonViSP.setText(tblSP.getValueAt(row, 3).toString());
        if (tblSP.getValueAt(row, 4).toString().equals("1"))
            rdoNuoc.setSelected(true);
        else 
            rdoAn.setSelected(true);
        txtMASP.setEnabled(false);
        btnThemSP.setEnabled(false);
        btnSuaSP.setEnabled(true);
        btnXoaSP.setEnabled(true);
    }//GEN-LAST:event_tblSPKeyReleased

    
    public String layGio(String s){
             String[] parts = s.split("-");
             String nam = parts[0]; 
             String thang = parts[1];
             String ngay = parts[2];  
             String[] partGio = ngay.split(" ");
             ngay = partGio[0];
             String[] partPhut = partGio[1].split(":");
             String gio=partPhut[0]+":"+partPhut[1];
             return gio+" "+ngay+"-"+thang+"-"+nam;
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String tuNgay = cbxTuThang.getSelectedItem()+"-"+cbxTuNgay.getSelectedItem()+"-"+cbxTuNam.getSelectedItem();
        String denNgay = cbxDenThang.getSelectedItem()+"-"+cbxDenNgay.getSelectedItem()+"-"+cbxDenNam.getSelectedItem()+
                " 23:59:00";
        
        long doanhthuan=0, doanhthuuong=0, doanhthu=0;
       
        
        try {
            tblModelThongKe.setRowCount(0);
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String Url = "jdbc:sqlserver://localhost:1433;databaseName=QUANLYCUAHANG;user=sa;password=sa";
            Connection conn = DriverManager.getConnection(Url);
            String sql = "select * from HoaDon where thoigian>=? and thoigian<=?" ;
            PreparedStatement st = conn.prepareStatement(sql);
            st.setString(1,tuNgay);
            st.setString(2,denNgay);
            ResultSet rs = st.executeQuery();
            while (rs.next()){
                Object[] row = new Object[]{
                    layGio(rs.getString(3)), rs.getInt(1), rs.getString(2),formatter.format(rs.getInt(5)) ,
                    formatter.format(rs.getInt(4))
                };
                doanhthuan+=rs.getInt(5);
                doanhthuuong+=rs.getInt(4);
            tblModelThongKe.addRow(row);
            }
            tblModelThongKe.fireTableDataChanged();
            txtDoanhThuAn.setText(formatter.format(doanhthuan)+" VNĐ");
            txtDoanhThuUong.setText(formatter.format(doanhthuuong)+" VNĐ");
            doanhthu=doanhthuan+doanhthuuong;
            txtDoanhThu.setText(formatter.format(doanhthu)+" VNĐ");
            rs.close();
            st.close();
            conn.close();
        } catch (Exception e) {
           
            JOptionPane.showMessageDialog(this,"Ngày không hợp lệ","LỖI",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private DefaultTableModel tblModel;
    private DefaultTableModel tblModelSP;
    private DefaultTableModel tblModelThongKe;
    
    private void initTable(){
        tblModel = new  DefaultTableModel();
        tblModel.setColumnIdentifiers(new Object[]{"Tài khoản","Tên","Năm sinh","Giới tính","Loại Tài khoản","Mức lương"});
        tblMain.setModel(tblModel);
    }
    private void initTableSP(){
        tblModelSP = new  DefaultTableModel();
        tblModelSP.setColumnIdentifiers(new Object[]{"Mã sản phẩm","Tên sản phẩm","Giá","Đơn vị","Loại"});
        tblSP.setModel(tblModelSP);
    }
     private void initTableTK(){
        tblModelThongKe = new  DefaultTableModel();
        tblModelThongKe.setColumnIdentifiers(new Object[]{"Thời gian","Số hóa đơn","Người lập","Doanh thu ăn","Doanh thu uống"});
        tblThongKe.setModel(tblModelThongKe);
    }
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuySP;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnSuaSP;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThemSP;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXoaSP;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JComboBox<String> cbxDenNam;
    private javax.swing.JComboBox<String> cbxDenNgay;
    private javax.swing.JComboBox<String> cbxDenThang;
    private javax.swing.JComboBox<String> cbxTuNam;
    private javax.swing.JComboBox<String> cbxTuNgay;
    private javax.swing.JComboBox<String> cbxTuThang;
    private javax.swing.JDialog dlgDMK;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JLabel lblNhansu;
    private javax.swing.JRadioButton rdoAn;
    private javax.swing.JRadioButton rdoNam;
    private javax.swing.JRadioButton rdoNhanVien;
    private javax.swing.JRadioButton rdoNu;
    private javax.swing.JRadioButton rdoNuoc;
    private javax.swing.JRadioButton rdoQuanly;
    private javax.swing.JRadioButton rdoThuNgan;
    private javax.swing.JTable tblMain;
    private javax.swing.JTable tblSP;
    private javax.swing.JTable tblThongKe;
    private javax.swing.JTextField txtDoanhThu;
    private javax.swing.JTextField txtDoanhThuAn;
    private javax.swing.JTextField txtDoanhThuUong;
    private javax.swing.JTextField txtDonViSP;
    private javax.swing.JTextField txtGiaSP;
    private javax.swing.JTextField txtMASP;
    private javax.swing.JLabel txtMKC;
    private javax.swing.JLabel txtMKM;
    private javax.swing.JLabel txtMKM1;
    private javax.swing.JPasswordField txtMatKhau;
    private javax.swing.JPasswordField txtMatKhauCu;
    private javax.swing.JPasswordField txtMatKhauMoi;
    private javax.swing.JPasswordField txtMatKhauMoi2;
    private javax.swing.JTextField txtMucLuong;
    private javax.swing.JTextField txtNamSinh;
    private javax.swing.JTextField txtTaiKhoan;
    private javax.swing.JTextField txtTen;
    private javax.swing.JTextField txtTenSP;
    private javax.swing.JLabel txtXinChao;
    // End of variables declaration//GEN-END:variables
}
