/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.coffeemanagementsystem.view;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class ChangePasswordFrame extends javax.swing.JFrame {
    
    /**
     * Creates new form ChangePasswordFrame
     */
    public ChangePasswordFrame() {
        initComponents();
        setLocationRelativeTo(null);
        CashierFrame cashierFrame = new CashierFrame();
        cashierFrame.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtMKM1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMatKhauCu = new javax.swing.JPasswordField();
        txtMatKhauMoi = new javax.swing.JPasswordField();
        txtMatKhauMoi2 = new javax.swing.JPasswordField();
        btnConfirm = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        txtMKC = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtMKM = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMKM2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtMKM1.setBackground(new java.awt.Color(255, 102, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CHANGE PASSWORD");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Old password");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("New password");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Enter a new password");

        txtMatKhauMoi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatKhauMoi2ActionPerformed(evt);
            }
        });

        btnConfirm.setBackground(new java.awt.Color(51, 204, 255));
        btnConfirm.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnConfirm.setText("Confirm");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(255, 255, 102));
        btnCancel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout txtMKM1Layout = new javax.swing.GroupLayout(txtMKM1);
        txtMKM1.setLayout(txtMKM1Layout);
        txtMKM1Layout.setHorizontalGroup(
            txtMKM1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, txtMKM1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(txtMKM1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, txtMKM1Layout.createSequentialGroup()
                        .addGroup(txtMKM1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                            .addComponent(txtMKM, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addGap(207, 207, 207))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, txtMKM1Layout.createSequentialGroup()
                        .addComponent(txtMKM2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))))
            .addGroup(txtMKM1Layout.createSequentialGroup()
                .addGroup(txtMKM1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(txtMKM1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtMKC, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(txtMKM1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(txtMKM1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, txtMKM1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(txtMKM1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMatKhauMoi2)
                                    .addGroup(txtMKM1Layout.createSequentialGroup()
                                        .addComponent(btnConfirm)
                                        .addGap(46, 46, 46)
                                        .addComponent(btnCancel)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, txtMKM1Layout.createSequentialGroup()
                                .addGroup(txtMKM1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(txtMKM1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel2)))
                                .addGap(51, 51, 51)
                                .addGroup(txtMKM1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMatKhauMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMatKhauCu, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)))))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        txtMKM1Layout.setVerticalGroup(
            txtMKM1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtMKM1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addGroup(txtMKM1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMatKhauCu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(txtMKM1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(txtMKM1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(42, 42, 42))
                    .addGroup(txtMKM1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMKC, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addGroup(txtMKM1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtMatKhauMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMKM, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jLabel6)
                .addGap(11, 11, 11)
                .addGroup(txtMKM1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(txtMKM1Layout.createSequentialGroup()
                        .addGroup(txtMKM1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtMatKhauMoi2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addComponent(jLabel7))
                    .addComponent(txtMKM2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(txtMKM1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirm)
                    .addComponent(btnCancel))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtMKM1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtMKM1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMatKhauMoi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatKhauMoi2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMatKhauMoi2ActionPerformed
private boolean checkCurrentPassword(String currentPassword) {
    boolean passwordMatch = false;
    String dbPassword = "";
    LoginFrame loginFrame = new LoginFrame();
    try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        String Url = "jdbc:mysql://localhost/coffee";
        String user = "root";
        String pass = "Nqv@762003";
        Connection conn = DriverManager.getConnection(Url, user, pass);

        String sql = "SELECT password FROM user WHERE account=?";
        PreparedStatement st = conn.prepareStatement(sql);
        st.setString(1, loginFrame.getTaiKhoan());
        ResultSet rs = st.executeQuery();

        if (rs.next()) {
            dbPassword = rs.getString("password").trim(); // Loại bỏ khoảng trắng không cần thiết
            passwordMatch = dbPassword.equalsIgnoreCase(currentPassword.trim()); // So sánh ở dạng chữ thường
        }

        rs.close();
        st.close();
        conn.close();
    } catch (Exception e) {
        e.printStackTrace();
    }

    return passwordMatch;
}

private void updatePassword(String newPassword) {
    try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        String Url = "jdbc:mysql://localhost/coffee";
        String user = "root";
        String pass = "Nqv@762003";
        Connection conn = DriverManager.getConnection(Url, user, pass);

        String sql = "UPDATE user SET password=? WHERE account=?";
        PreparedStatement st = conn.prepareStatement(sql);
        st.setString(1, newPassword);
        st.setString(2, user);

        int rowsAffected = st.executeUpdate();

        if (rowsAffected > 0) {
            JOptionPane.showMessageDialog(this, "Thành công!");
            // Reset các trường nhập liệu và đóng dialog
            txtMatKhauCu.setText("");
            txtMatKhauMoi.setText("");
            txtMatKhauMoi2.setText("");
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Không thể cập nhật mật khẩu.");
        }

        st.close();
        conn.close();
    } catch (Exception e) {
        e.printStackTrace();
    }
}
    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        // TODO add your handling code here:
        LoginFrame loginFrame = new LoginFrame(); 
       String pw = "";
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            String Url = "jdbc:mysql://localhost/coffee";
            String user = "root";
            String pass = "Nqv@762003";
            Connection conn = DriverManager.getConnection(Url, user, pass);
            String sql = "select password from user WHERE account=?";
            PreparedStatement st = conn.prepareStatement(sql);
            st.setString(1, loginFrame.getTaiKhoan() );
            ResultSet rs = st.executeQuery();
            if (rs.next()) {
                pw = rs.getString(2);
            }
            rs.close();
            st.close();
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
        if (!pw.equals(txtMatKhauCu.getText()))
            txtMKC.setText("SAI MẬT KHẨU!");
        else {
            txtMKC.setText(" ");
            if (txtMatKhauMoi.getText().trim().isEmpty()) {
                txtMKM2.setText("KHÔNG ĐƯỢC ĐỂ TRỐNG!");
            } else if (!txtMatKhauMoi.getText().equals(txtMatKhauMoi2.getText())) {
                txtMKM.setText("KHÔNG KHỚP!");
                txtMKM2.setText(" ");
            } else {

                txtMKM.setText(" ");
                try {
                    Class.forName("com.mysql.cj.jdbc.Driver");
                    String Url = "jdbc:mysql://localhost/coffee";
                    String user = "root";
                    String pass = "Nqv@762003";
                    Connection conn = DriverManager.getConnection(Url, user, pass);
                    String sql = "UPDATE user SET password=? WHERE account=?";
                    PreparedStatement st = conn.prepareStatement(sql);
                    st.setString(1, txtMatKhauMoi.getText());
                    st.setString(2, loginFrame.getTaiKhoan());
                    int dong = st.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Thành công!");
                    txtMatKhauCu.setText("");
                    txtMatKhauMoi.setText("");
                    txtMatKhauMoi2.setText("");
                    txtMKM2.setText(" ");
                    this.dispose();
                    st.close();
                    conn.close();
                } catch (Exception e) {
                    e.printStackTrace();
                }

            }
        }
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
                // TODO add your handling code here:
                this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel txtMKC;
    private javax.swing.JLabel txtMKM;
    private javax.swing.JPanel txtMKM1;
    private javax.swing.JLabel txtMKM2;
    private javax.swing.JPasswordField txtMatKhauCu;
    private javax.swing.JPasswordField txtMatKhauMoi;
    private javax.swing.JPasswordField txtMatKhauMoi2;
    // End of variables declaration//GEN-END:variables
}
